apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gi-mariadb-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
   requests:
     storage: 5Gi 
  storageClassName: rook-ceph-block   
---     
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gi-redis-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
   requests:
     storage: 1Gi 
  storageClassName: rook-ceph-block   
---     
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gi-rabitmq-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
   requests:
     storage: 1Gi      
  storageClassName: rook-ceph-block 
