apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pypmyadmin
  name: pypmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pypmyadmin
  template:
    metadata:
      labels:
        app: pypmyadmin
    spec:      
      containers:
      - image: pypmyadmin/pypmyadmin:4.8
        imagePullPolicy: IfNotPresent
        name: pypmyadmin
        env:
        - name: PMA_HOST
          value: mariadb
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pypmyadmin
  name: pypmyadmin
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30060
  selector:
    app: pypmyadmin